//go:build !ignore_autogenerated

/*
Copyright 2026 Fábio Matavelli.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterResourceConfig) DeepCopyInto(out *ClusterResourceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterResourceConfig.
func (in *ClusterResourceConfig) DeepCopy() *ClusterResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceMappingConfig) DeepCopyInto(out *DeviceMappingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceMappingConfig.
func (in *DeviceMappingConfig) DeepCopy() *DeviceMappingConfig {
	if in == nil {
		return nil
	}
	out := new(DeviceMappingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericResourceConfig) DeepCopyInto(out *GenericResourceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericResourceConfig.
func (in *GenericResourceConfig) DeepCopy() *GenericResourceConfig {
	if in == nil {
		return nil
	}
	out := new(GenericResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeraldConfig) DeepCopyInto(out *HeraldConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeraldConfig.
func (in *HeraldConfig) DeepCopy() *HeraldConfig {
	if in == nil {
		return nil
	}
	out := new(HeraldConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeraldConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeraldConfigList) DeepCopyInto(out *HeraldConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HeraldConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeraldConfigList.
func (in *HeraldConfigList) DeepCopy() *HeraldConfigList {
	if in == nil {
		return nil
	}
	out := new(HeraldConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeraldConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeraldConfigSpec) DeepCopyInto(out *HeraldConfigSpec) {
	*out = *in
	in.NetBox.DeepCopyInto(&out.NetBox)
	out.Resync = in.Resync
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeraldConfigSpec.
func (in *HeraldConfigSpec) DeepCopy() *HeraldConfigSpec {
	if in == nil {
		return nil
	}
	out := new(HeraldConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeraldConfigStatus) DeepCopyInto(out *HeraldConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.NetBox.DeepCopyInto(&out.NetBox)
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeraldConfigStatus.
func (in *HeraldConfigStatus) DeepCopy() *HeraldConfigStatus {
	if in == nil {
		return nil
	}
	out := new(HeraldConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedTagConfig) DeepCopyInto(out *ManagedTagConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedTagConfig.
func (in *ManagedTagConfig) DeepCopy() *ManagedTagConfig {
	if in == nil {
		return nil
	}
	out := new(ManagedTagConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxConfig) DeepCopyInto(out *NetBoxConfig) {
	*out = *in
	out.TokenSecretRef = in.TokenSecretRef
	in.TLS.DeepCopyInto(&out.TLS)
	out.VersionCheck = in.VersionCheck
	out.ManagedTag = in.ManagedTag
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxConfig.
func (in *NetBoxConfig) DeepCopy() *NetBoxConfig {
	if in == nil {
		return nil
	}
	out := new(NetBoxConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxStatus) DeepCopyInto(out *NetBoxStatus) {
	*out = *in
	if in.LastCheckedTime != nil {
		in, out := &in.LastCheckedTime, &out.LastCheckedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxStatus.
func (in *NetBoxStatus) DeepCopy() *NetBoxStatus {
	if in == nil {
		return nil
	}
	out := new(NetBoxStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodesResourceConfig) DeepCopyInto(out *NodesResourceConfig) {
	*out = *in
	out.Device = in.Device
	out.VirtualMachine = in.VirtualMachine
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodesResourceConfig.
func (in *NodesResourceConfig) DeepCopy() *NodesResourceConfig {
	if in == nil {
		return nil
	}
	out := new(NodesResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCIDRsResourceConfig) DeepCopyInto(out *PodCIDRsResourceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCIDRsResourceConfig.
func (in *PodCIDRsResourceConfig) DeepCopy() *PodCIDRsResourceConfig {
	if in == nil {
		return nil
	}
	out := new(PodCIDRsResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceStatuses) DeepCopyInto(out *ResourceStatuses) {
	*out = *in
	in.Cluster.DeepCopyInto(&out.Cluster)
	in.Nodes.DeepCopyInto(&out.Nodes)
	in.Services.DeepCopyInto(&out.Services)
	in.PodCIDRs.DeepCopyInto(&out.PodCIDRs)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceStatuses.
func (in *ResourceStatuses) DeepCopy() *ResourceStatuses {
	if in == nil {
		return nil
	}
	out := new(ResourceStatuses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSyncStatus) DeepCopyInto(out *ResourceSyncStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSyncStatus.
func (in *ResourceSyncStatus) DeepCopy() *ResourceSyncStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcesConfig) DeepCopyInto(out *ResourcesConfig) {
	*out = *in
	out.Cluster = in.Cluster
	out.Nodes = in.Nodes
	out.Services = in.Services
	out.PodCIDRs = in.PodCIDRs
	if in.Additional != nil {
		in, out := &in.Additional, &out.Additional
		*out = make(map[string]GenericResourceConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcesConfig.
func (in *ResourcesConfig) DeepCopy() *ResourcesConfig {
	if in == nil {
		return nil
	}
	out := new(ResourcesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResyncConfig) DeepCopyInto(out *ResyncConfig) {
	*out = *in
	out.Interval = in.Interval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResyncConfig.
func (in *ResyncConfig) DeepCopy() *ResyncConfig {
	if in == nil {
		return nil
	}
	out := new(ResyncConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicesResourceConfig) DeepCopyInto(out *ServicesResourceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicesResourceConfig.
func (in *ServicesResourceConfig) DeepCopy() *ServicesResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ServicesResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.CABundleSecretRef != nil {
		in, out := &in.CABundleSecretRef, &out.CABundleSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionCheckConfig) DeepCopyInto(out *VersionCheckConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionCheckConfig.
func (in *VersionCheckConfig) DeepCopy() *VersionCheckConfig {
	if in == nil {
		return nil
	}
	out := new(VersionCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineMappingConfig) DeepCopyInto(out *VirtualMachineMappingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineMappingConfig.
func (in *VirtualMachineMappingConfig) DeepCopy() *VirtualMachineMappingConfig {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineMappingConfig)
	in.DeepCopyInto(out)
	return out
}
